spring.application.name=merchant-service
server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5433/merchant
spring.datasource.username=payhub
spring.datasource.password=payhub
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.autoconfigure.exclude=org.springframework.boot.security.oauth2.server.resource.autoconfigure.servlet.OAuth2ResourceServerAutoConfiguration
