spring.application.name=reporting-service
server.port=8088
spring.datasource.url=jdbc:postgresql://localhost:5438/reporting
spring.datasource.username=payhub
spring.datasource.password=payhub
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
