spring.application.name=risk-service
server.port=8085
spring.datasource.url=jdbc:postgresql://localhost:5435/risk
spring.datasource.username=payhub
spring.datasource.password=payhub
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
