spring.application.name=reconciliation-service
server.port=8087
spring.datasource.url=jdbc:postgresql://localhost:5437/reconciliation
spring.datasource.username=payhub
spring.datasource.password=payhub
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
