spring.application.name=rail-adapter-service
server.port=8086
spring.datasource.url=jdbc:postgresql://localhost:5436/rail
spring.datasource.username=payhub
spring.datasource.password=payhub
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
