spring:
  datasource:
    url: jdbc:postgresql://postgres-merchant:5432/merchant
    username: ${DB_USERNAME:payhub}
    password: ${DB_PASSWORD:payhub}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
