server:
  port: 8310
management:
  server:
    port: 8311
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/orchestrator
    username: ${DB_USERNAME:payhub}
    password: ${DB_PASSWORD:payhub}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
