spring:
  application:
    name: payment-orchestrator
  autoconfigure:
    exclude: org.springframework.boot.security.oauth2.server.resource.autoconfigure.servlet.OAuth2ResourceServerAutoConfiguration

payhub:
  finledger:
    base-url: ${FINLEDGER_BASE_URL:http://localhost:8080}
  clients:
    risk-service: ${PAYHUB_CLIENTS_RISK_SERVICE:http://localhost:8320}
    rail-adapter-service: ${PAYHUB_CLIENTS_RAIL_ADAPTER_SERVICE:http://localhost:8330}
    merchant-service: ${PAYHUB_CLIENTS_MERCHANT_SERVICE:http://localhost:8300}
