server:
  port: 8400
management:
  server:
    port: 8401
spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/reconciliation
    username: ${DB_USERNAME:payhub}
    password: ${DB_PASSWORD:payhub}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
