server:
  port: 8410
management:
  server:
    port: 8411
spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/reporting
    username: ${DB_USERNAME:payhub}
    password: ${DB_PASSWORD:payhub}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
payhub:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
