spring:
  datasource:
    url: jdbc:postgresql://postgres-risk:5432/risk
    username: ${DB_USERNAME:payhub}
    password: ${DB_PASSWORD:payhub}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
