spring.application.name=notification-service
server.port=8089
spring.datasource.url=jdbc:postgresql://localhost:5439/notification
spring.datasource.username=payhub
spring.datasource.password=payhub
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
