package com.payhub.orchestrator.domain;

public enum PaymentStatus {
    CREATED,
    RISK_PENDING,
    RISK_APPROVED,
    RISK_REJECTED,
    RISK_REVIEW,
    RAIL_SUBMITTED,
    SETTLEMENT_PENDING,
    SETTLED,
    FAILED_FINAL,
    RECONCILIATION_REQUIRED,
    REFUND_REQUESTED,
    REFUND_RAIL_SUBMITTED,
    REFUND_SETTLEMENT_PENDING,
    REFUND_SETTLED,
    REFUND_FAILED_FINAL,
    REFUND_RECONCILIATION_REQUIRED
}
